version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-chat-backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - USE_ONLINE_LLM=true  # Set to false to use local LLM (llama3 via Ollama)
      - LLM_URL= http://ollama:11434/api/chat
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}



  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai-chat-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama-models:/root/.ollama

volumes:
  ollama-models:
