

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-chat-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - USE_ONLINE_LLM
      - LLM_URL
      - LLM_API_KEY



  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai-chat-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

