services:
  backend:
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama-models:/root/.ollama

volumes:
  ollama-models:
